model: 
  type: VQVAE
  obs_dim: [11, 1]
  ac_dim:  [30, 7]
  latent_dim: 60 
  hidden: [180, 90, 60]

dataloader: 
  raw_data: "/extra_storage/three_piece_assembly_latent_actions/buf.pkl"
  n_val: 10
  n_test: 2
  ac_chunk: 30 
  obs_dim: 11
  ac_dim: 7 
  batch_size: 50


optim: 
  lr: 1.0e-1
  log_freq: 100
  save_freq: 1000
  epochs: 20

train_dir: /home/blank/latent-diffusion-policy/latent_actions/VQlr1