model: 
  type: VQVAE
  obs_dim: [9, 1]
  ac_dim:  [30, 10]
  latent_dim: 75
  hidden: [300, 300, 300, 300]
  n_embeddings: 256

dataloader: 
  raw_data: "/extra_storage/equicontact_stacking_fixed_pose_sa/buf.pkl"
  n_val: 20
  n_test: 5
  ac_chunk: 30
  obs_dim: 9
  ac_dim: 7 
  batch_size: 50


optim: 
  lr: 0.0005
  log_freq: 100
  save_freq: 1000
  epochs: 100

train_dir: /home/blank/cs282_project/latent_actions/mlp_vqvae_equicontact