model: 
  type: VAE
  ac_chunk: 32
  obs_dim : [9, 1]
  ac_dim : [32, 10]
  latent_dim : 256
  channels : [64,128,256]
  dec_in_padding : [1, 1, 1]
  dec_out_padding : [1, 1, 1]

dataloader: 
  raw_data: "/extra_storage/threading_latent_actions/buf.pkl"
  n_val: 10
  n_test: 2
  ac_chunk: 32
  obs_dim: 9
  ac_dim: 10
  batch_size: 50


optim: 
  lr: 0.003
  log_freq: 100
  save_freq: 1000
  epochs: 100

train_dir: /home/blank/cs282_project/latent_actions/cnn_vae_threading